name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          poetry --version
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test All
        env:
          CRED_PATH: ${{vars.CRED_PATH}}
          SYSTEM_WALLET_PRIVATE_KEY_PATH: ${{vars.PROPOSAL_NFT_CONTRACT_ADDRESS}}
          GOOGLE_CLOUD_STORAGE_BUCKET_NAME: ${{vars.GOOGLE_CLOUD_STORAGE_BUCKET_NAME}}
          PROVIDE_NETWORK: ${{vars.PROVIDE_NETWORK}}
          PROPOSAL_NFT_CONTRACT_ADDRESS: ${{vars.PROPOSAL_NFT_CONTRACT_ADDRESS}}
          DEFAULT_SLACK_INCOMING_WEBHOOKS_URL: ${{vars.DEFAULT_SLACK_INCOMING_WEBHOOKS_URL}}
          DEV_PRIVATE_KEY: ${{secrets.DEV_PRIVATE_KEY}}
          GOOGLE_CLOUD_KEY: ${{vars.GOOGLE_CLOUD_KEY}}
        run: |
          mkdir -p key/firebase key/wallet
          echo-n $GOOGLE_CLOUD_KEY | base64 --decode > $CRED_PATH
          echo-n $DEV_PRIVATE_KEY | base64 --decode > $SYSTEM_WALLET_PRIVATE_KEY_PATH
          poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt
      - name: Comment to PR
        uses: MishaKav/pytest-coverage-comment@main
        if: ${{ github.event_name == 'pull_request' }}
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml